# Generated by Django 4.0.6 on 2022-07-22 06:03

import annotators.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='project title')),
                ('description', models.TextField(verbose_name='project description')),
                ('class_list', models.JSONField(verbose_name='class list')),
                ('class_num', models.IntegerField(verbose_name='class number')),
                ('file_weight', models.FileField(blank=True, null=True, upload_to=annotators.models.project_model_weight_dir, verbose_name='model weight')),
                ('annotators', models.ManyToManyField(related_name='annotators', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='<django.db.models.fields.related.ForeignKey>/images')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='date uploaded')),
                ('annotate_at', models.DateTimeField(auto_now=True)),
                ('polygons', models.JSONField(verbose_name='annotate polygons')),
                ('boxes', models.JSONField(verbose_name='annotate boxes')),
                ('annotate_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotators.annotationproject')),
            ],
        ),
    ]
