# Generated by Django 4.0.6 on 2022-07-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationproject',
            name='annotation_type',
            field=models.CharField(choices=[('PT', 'Point'), ('PL', 'Polygon'), ('BB', 'Bounding Box')], default='PL', max_length=2),
        ),
        migrations.AddField(
            model_name='annotationproject',
            name='auto_annotate',
            field=models.BooleanField(default=False, verbose_name='auto annotate'),
        ),
        migrations.AddField(
            model_name='annotationproject',
            name='is_video',
            field=models.BooleanField(default=False, verbose_name='is video'),
        ),
    ]
