# Generated by Django 4.0.6 on 2022-07-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotators', '0003_alter_image_boxes_alter_image_polygons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='boxes',
            field=models.JSONField(blank=True, null=True, verbose_name='annotate boxes'),
        ),
        migrations.AlterField(
            model_name='image',
            name='polygons',
            field=models.JSONField(blank=True, null=True, verbose_name='annotate polygons'),
        ),
    ]
