# Generated by Django 4.0.6 on 2022-07-23 13:36

import annotators.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotators', '0004_alter_image_boxes_alter_image_polygons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='annotate_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to=annotators.models.image_dir),
        ),
    ]
